### ISSUE TITLE
Provide a setVersion task

### ISSUE THREAD

**Issue by stewartbryson** [epitschke/gradle-file-versioning#1]
Instead of having to always bump a version, it would be nice to have a `setVersion` (or similar) task that takes a version number as a parameter and creates or updates the text file. Of course, we can easily just write a version to the text file, but this would make the plugin more complete.

Thank you.

**Comment by epitschke** [comment]
Hi Stewart,
   thank you for your response. I planned to do a maintenance release and i think this would be a very nice addition.
Regards
   Elmar

**Comment by epitschke** [comment]
Hi Stewart,
   the new Version (1.1.0), including your request, has just been released and uploaded to the gradle plugin portal.I hope you enjoy it.
Regards
   Elmar

**Comment by stewartbryson** [comment]
Thanks so much. I’ll give it a try today.
