### ISSUE TITLE
Getting the version information.

### ISSUE THREAD

**Issue by stewartbryson** [epitschke/gradle-file-versioning#4]
I usually do something like with `maven-publish`:

```
ext.publishUrl = "gcs://my-bucket/${version.endsWith('SNAPSHOT') ? "snapshot" : "release"}"
```

I don't see where the version is available in the plugin. If it's there, could you point me in that direction? If not, could you add a public field or method that exposes it?

**Comment by epitschke** [comment]
Hi Stewart,
   the issue here is that the ext block gets executed before the lifecycle of the plugin kicks in. So at that time the variable "version" or "project.version" is undefined. Inside a task on the other hand you will get the correct version this way.
I will try to add a static method to access this information at the time the ext block get executed. I will keep you informed
Regards
    Elmar

**Comment by epitschke** [comment]
Sorry, did not mean to close the ticket just yet. My default commit merge message has the close command, sorry for that

**Comment by epitschke** [comment]
Hi Stewart,
    the version 1.3.0 has been release. Can you check if this satisfies your needs?
Regards
    Elmar

**Comment by stewartbryson** [comment]
Thanks for working on this. Your code sample in the documentation doesn't work for me... I hope I'm not missing something very simple. Gradle doesn't know anything about `de`:

```
Could not get unknown property 'de' for object of type org.gradle.internal.extensibility.DefaultExtraPropertiesExtension
```

**Comment by epitschke** [comment]
Hi Stewart,
   right, the class was missing in the README. So instead of 

> de.epitschke.gradle.fileversioning.getVersionFromFile()

 it should be

> de.epitschke.gradle.fileversioning.**FileVersioningPlugin**.getVersionFromFile()

I fixed that in the README. Can you change this on your side? - It should work then
Regards
    Elmar

**Comment by stewartbryson** [comment]
Works perfectly. Thank you.
